project                 = "xenon-pager-436506-m9"      
region                  = "europe-north1"
zone                    = "europe-north1-a"
machine_type_small      = "e2-small"
machine_type_medium     = "e2-medium"
ssh_user                = "gcp_hrung"